// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-blockchain/internal/api/controllers"
	"go-blockchain/internal/api/server"
	"go-blockchain/internal/common/log"
	"go-blockchain/internal/services"
)

// Injectors from wire.go:

func InitApp() (App, error) {
	sugaredLogger := log.SugaredLogger()
	healthController := controllers.NewHealthController(sugaredLogger)
	blockServiceImpl := services.NewBlockServiceImpl(sugaredLogger)
	blockController := controllers.NewBlockController(blockServiceImpl, sugaredLogger)
	routerConfig := server.NewRouter(healthController, blockController)
	serverServer := server.NewServer(sugaredLogger, routerConfig)
	app := NewApp(serverServer)
	return app, nil
}
